### ISSUE TITLE
image: no appropriate protocol with ssl

### ISSUE THREAD

**Issue by turenar** [turenar/elnetw#75]
SSLv3が無効になったとかそこら辺の変更なんだろうか

12:56:01.230 [WARN  j.m.t.t.g.ImageViewerFrame$ImageFetcher] Error while fetching: https://pbs.twimg.com/media/B8U6d-0CUAIOAxg.jpg
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.Handshaker.activate(Unknown Source) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(Unknown Source) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_31]
	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:208) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.Connection.connect(Connection.java:161) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:246) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:186) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:375) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:328) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:196) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) ~[okhttp-1.5.4.jar:na]
	at com.squareup.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25) ~[okhttp-1.5.4.jar:na]
	at jp.mydns.turenar.twclient.internal.NetworkSupport.openConnection(NetworkSupport.java:177) [elnetw-core-0.2-rc1+dev-23-g1e34afb.jar:0.2-rc1+dev-23-g1e34afb]
	at jp.mydns.turenar.twclient.internal.NetworkSupport.fetchContents(NetworkSupport.java:94) [elnetw-core-0.2-rc1+dev-23-g1e34afb.jar:0.2-rc1+dev-23-g1e34afb]
	at jp.mydns.turenar.twclient.gui.ImageViewerFrame$ImageFetcher.run(ImageViewerFrame.java:124) [elnetw-core-0.2-rc1+dev-23-g1e34afb.jar:0.2-rc1+dev-23-g1e34afb]
	at jp.mydns.turenar.twclient.JobQueue$JobWorkerThread.run(JobQueue.java:123) [elnetw-core-0.2-rc1+dev-23-g1e34afb.jar:0.2-rc1+dev-23-g1e34afb]

**Comment by turenar** [comment]
こっちっぽい
httpsするの辞めるかあ
01:18:02.435 [WARN  t.t.g.ImageViewerFrame$ImageFetcher     worker-0] Error while fetching: https://pbs.twimg.com/media/B8nHGLfCIAANpOj.jpg
javax.net.ssl.SSLHandshakeException: server certificate change is restricted during renegotiation
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937) ~[na:1.8.0_31]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_31]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:292) ~[na:1.8.0_31]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1440) ~[na:1.8.0_31]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_31]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:957) ~[na:1.8.0_31]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:892) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391) ~[na:1.8.0_31]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_31]
	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:241) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.Connection.connect(Connection.java:158) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235) ~[okhttp-2.2.0.jar:na]
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:425) ~[okhttp-urlconnection-2.2.0.jar:na]
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:376) ~[okhttp-urlconnection-2.2.0.jar:na]
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:227) ~[okhttp-urlconnection-2.2.0.jar:na]
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) ~[okhttp-urlconnection-2.2.0.jar:na]
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25) ~[okhttp-urlconnection-2.2.0.jar:na]
	at jp.mydns.turenar.twclient.internal.NetworkSupport.openConnection(NetworkSupport.java:179) [bin/:na]
	at jp.mydns.turenar.twclient.internal.NetworkSupport.fetchContents(NetworkSupport.java:96) [bin/:na]
	at jp.mydns.turenar.twclient.gui.ImageViewerFrame$ImageFetcher.run(ImageViewerFrame.java:124) [bin/:na]
	at jp.mydns.turenar.twclient.JobQueue$JobWorkerThread.run(JobQueue.java:124) [bin/:na]
